// Generated by CoffeeScript 1.9.2
(function() {
  var $, Core;

  $ = function(selector, context) {
    return new Core(selector, context);
  };

  $.isArray = require('./isArray');

  $.each = require('./each');

  Core = function(selector, context) {
    var elems;
    context = context || document;
    elems = context.querySelectorAll(selector);
    Array.prototype.push.apply(this, elems);
    this.context = context;
    this.selector = selector;
    return this;
  };

  Core.prototype = {
    addClass: function(cName) {
      var arr;
      arr = this.get(0).className.split(" ");
      if (arr.indexOf(cName) > -1) {
        return;
      }
      arr.push(cName);
      return this.get(0).className = arr.join(" ");
    },
    removeClass: function(cName) {
      var arr, c, classArray, j, len;
      arr = this.get(0).className.split(" ");
      if (arr.indexOf(cName) === -1) {
        return;
      }
      classArray = [];
      for (j = 0, len = arr.length; j < len; j++) {
        c = arr[j];
        if (c !== cName && c !== "") {
          classArray.push(c);
        }
      }
      return this.get(0).className = classArray.join(" ");
    },
    each: function(callback) {
      var i, j, l, ref;
      i = 0;
      l = this.length;
      for (i = j = 0, ref = l; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        callback.call(this, this[i], i);
      }
    },
    get: function(index) {
      var i, j, l, ref, ret;
      ret = [];
      l = this.length;
      for (i = j = 0, ref = l; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        ret.push(this[i]);
      }
      if (typeof index === 'number') {
        ret = ret[index];
      }
      return ret;
    },
    splice: Array.prototype.splice
  };

  window.$ = $;

  require('./test');

  return;

}).call(this);
